language: php
php:
  - 7.0
notifications:
  email: false
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE splc2017;'
  - sudo apt-get install -y httrack
  - sudo apt-get install -y webhttrack
  - composer self-update
  - composer install
  - composer update
before_deploy:
  - rm -rf .git
  - mkdir build
  - zip -r build/generacion-estatica.zip ./*

deploy:
  provider: releases
  api_key: a46e624318d1b8e518215352766bb596b46002b9
  acl: public_read
  local_dir: build
  bucket: "egc-generacionestatica"
  skip_cleanup: true
  on:
    branch: release