language: php
php:
  - 7.0
notifications:
  email: false
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE splc2017;'
  - sudo apt-get install -y httrack
  - sudo apt-get install -y webhttrack
  - composer self-update
  - composer install
  - composer update
before_deploy:
  - rm -rf .git
  - mkdir build
  - zip -r build/generacion-estatica.zip ./*

deploy:
  provider: releases
  api_key: b3e5f47472072a18568b6b1df44469c352a5dcb0
  acl: public_read
  local_dir: build
  bucket: "egc-generacionestatica"
  skip_cleanup: true
  on:
    branch: release