language: php
php:
  - 7.0
notifications:
  email: false
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE splc2017;'
  - sudo apt-get install -y httrack
  - sudo apt-get install -y webhttrack
  - composer self-update
  - composer install
  - composer update
before_deploy:
  - git config --local user.name "Adelay95"
  - git config --local user.email "franciscojavierhigueras@gmail.com"
  - rm -rf .git
  - mkdir build
  - zip -r build/generacion-estatica.zip ./*

deploy:
  provider: releases
  api_key: b5f5621a0e5bbb1199e111487b1de358f14c19c7
  file: build/*
  skip_cleanup: true
  on:
    branch: release
